# Generated by Django 5.0.1 on 2024-02-06 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0003_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField(default=False)),
            ],
        ),
    ]
