# Generated by Django 5.0.1 on 2024-02-08 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0007_student_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminApproval',
        ),
    ]
